DROP TABLE IF EXISTS CARRIER;
CREATE TABLE CARRIER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  carrier_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  phone VARCHAR(12) DEFAULT NULL
);

